-- TRanne il Lunedì V26 — coda notifiche e promemoria
-- Eseguire UNA VOLTA in Supabase > SQL Editor.

create table if not exists public.notification_jobs (
  id bigint generated by default as identity primary key,
  kind text not null,
  booking_id uuid references public.bookings(id) on delete cascade,
  recipient_type text not null check (recipient_type in ('admin','customer','all')),
  recipient_external_id text,
  title text not null,
  message text not null,
  scheduled_for timestamptz not null default now(),
  status text not null default 'pending' check (status in ('pending','sent','failed','cancelled')),
  attempts integer not null default 0,
  sent_at timestamptz,
  provider_message_id text,
  last_error text,
  dedupe_key text not null unique,
  created_at timestamptz not null default now()
);
alter table public.notification_jobs enable row level security;
revoke all on table public.notification_jobs from public, anon, authenticated;

create or replace function public.enqueue_booking_notifications()
returns trigger language plpgsql security definer set search_path=public,pg_temp as $$
declare
  c public.customers%rowtype;
  appointment_at timestamptz;
  ext_id text;
  pretty_date text;
  pretty_time text;
begin
  select * into c from public.customers where id = new.customer_id;
  appointment_at := (new.booking_date + new.booking_time) at time zone 'Europe/Rome';
  ext_id := case when c.phone is not null and c.phone not like 'MANUAL-%' then 'cliente_' || regexp_replace(c.phone,'[^0-9]','','g') else null end;
  pretty_date := to_char(new.booking_date, 'DD/MM/YYYY');
  pretty_time := to_char(new.booking_time, 'HH24:MI');

  if tg_op = 'INSERT' and new.status = 'confirmed' then
    insert into public.notification_jobs(kind,booking_id,recipient_type,title,message,scheduled_for,dedupe_key)
    values ('new_booking',new.id,'admin','💈 Nuova prenotazione',c.first_name || ' ' || c.last_name || ' — ' || pretty_date || ' alle ' || pretty_time,now(),'admin-new-'||new.id)
    on conflict do nothing;
  elsif tg_op = 'UPDATE' and new.status='confirmed' and (old.booking_date,old.booking_time) is distinct from (new.booking_date,new.booking_time) then
    update public.notification_jobs set status='cancelled' where booking_id=new.id and status='pending' and kind in ('reminder_24h','reminder_1h');
    insert into public.notification_jobs(kind,booking_id,recipient_type,title,message,scheduled_for,dedupe_key)
    values ('booking_moved',new.id,'admin','🔄 Appuntamento spostato',c.first_name || ' ' || c.last_name || ' → ' || pretty_date || ' alle ' || pretty_time,now(),'admin-moved-'||new.id||'-'||extract(epoch from now())::bigint)
    on conflict do nothing;
    if ext_id is not null then
      insert into public.notification_jobs(kind,booking_id,recipient_type,recipient_external_id,title,message,scheduled_for,dedupe_key)
      values ('customer_moved',new.id,'customer',ext_id,'Appuntamento aggiornato','Il tuo appuntamento è stato spostato al '||pretty_date||' alle '||pretty_time||'.',now(),'customer-moved-'||new.id||'-'||extract(epoch from now())::bigint)
      on conflict do nothing;
    end if;
  end if;

  if new.status='confirmed' and ext_id is not null and (tg_op='INSERT' or (old.booking_date,old.booking_time) is distinct from (new.booking_date,new.booking_time)) then
    if appointment_at - interval '24 hours' > now() then
      insert into public.notification_jobs(kind,booking_id,recipient_type,recipient_external_id,title,message,scheduled_for,dedupe_key)
      values ('reminder_24h',new.id,'customer',ext_id,'Promemoria appuntamento','Domani alle '||pretty_time||' ti aspettiamo da Tranne il Lunedì.',appointment_at-interval '24 hours','24h-'||new.id||'-'||new.booking_date||'-'||new.booking_time)
      on conflict do nothing;
    end if;
    if appointment_at - interval '1 hour' > now() then
      insert into public.notification_jobs(kind,booking_id,recipient_type,recipient_external_id,title,message,scheduled_for,dedupe_key)
      values ('reminder_1h',new.id,'customer',ext_id,'Appuntamento tra un’ora','Ti aspettiamo alle '||pretty_time||' da Tranne il Lunedì.',appointment_at-interval '1 hour','1h-'||new.id||'-'||new.booking_date||'-'||new.booking_time)
      on conflict do nothing;
    end if;
  end if;

  if tg_op='UPDATE' and old.status='confirmed' and new.status='cancelled' then
    update public.notification_jobs set status='cancelled' where booking_id=new.id and status='pending';
    if ext_id is not null then
      insert into public.notification_jobs(kind,booking_id,recipient_type,recipient_external_id,title,message,scheduled_for,dedupe_key)
      values ('customer_cancelled',new.id,'customer',ext_id,'Appuntamento annullato','Il tuo appuntamento del '||pretty_date||' alle '||pretty_time||' è stato annullato.',now(),'cancelled-'||new.id)
      on conflict do nothing;
    end if;
  end if;
  return new;
end; $$;

drop trigger if exists bookings_notification_trigger on public.bookings;
create trigger bookings_notification_trigger after insert or update of booking_date,booking_time,status on public.bookings
for each row execute function public.enqueue_booking_notifications();

-- Crea i promemoria per appuntamenti futuri già esistenti.
insert into public.notification_jobs(kind,booking_id,recipient_type,recipient_external_id,title,message,scheduled_for,dedupe_key)
select 'reminder_24h',b.id,'customer','cliente_'||regexp_replace(c.phone,'[^0-9]','','g'),'Promemoria appuntamento','Domani alle '||to_char(b.booking_time,'HH24:MI')||' ti aspettiamo da Tranne il Lunedì.',(b.booking_date+b.booking_time) at time zone 'Europe/Rome' - interval '24 hours','24h-'||b.id||'-'||b.booking_date||'-'||b.booking_time
from public.bookings b join public.customers c on c.id=b.customer_id
where b.status='confirmed' and c.phone not like 'MANUAL-%' and ((b.booking_date+b.booking_time) at time zone 'Europe/Rome')-interval '24 hours'>now()
on conflict do nothing;

insert into public.notification_jobs(kind,booking_id,recipient_type,recipient_external_id,title,message,scheduled_for,dedupe_key)
select 'reminder_1h',b.id,'customer','cliente_'||regexp_replace(c.phone,'[^0-9]','','g'),'Appuntamento tra un’ora','Ti aspettiamo alle '||to_char(b.booking_time,'HH24:MI')||' da Tranne il Lunedì.',(b.booking_date+b.booking_time) at time zone 'Europe/Rome' - interval '1 hour','1h-'||b.id||'-'||b.booking_date||'-'||b.booking_time
from public.bookings b join public.customers c on c.id=b.customer_id
where b.status='confirmed' and c.phone not like 'MANUAL-%' and ((b.booking_date+b.booking_time) at time zone 'Europe/Rome')-interval '1 hour'>now()
on conflict do nothing;
