-- =============================================================
-- TRANNE IL LUNEDÌ V27 — BACKEND NOTIFICHE COMPLETO
-- Eseguire UNA VOLTA in Supabase > SQL Editor.
-- Richiede le tabelle public.customers e public.bookings già esistenti.
-- =============================================================

create extension if not exists pgcrypto;

create table if not exists public.notification_jobs (
  id bigint generated by default as identity primary key,
  kind text not null,
  booking_id uuid references public.bookings(id) on delete cascade,
  recipient_type text not null check (recipient_type in ('admin','customer','all')),
  recipient_external_id text,
  title text not null,
  message text not null,
  scheduled_for timestamptz not null default now(),
  status text not null default 'pending'
    check (status in ('pending','processing','sent','failed','cancelled')),
  attempts integer not null default 0,
  locked_at timestamptz,
  sent_at timestamptz,
  provider_message_id text,
  last_error text,
  dedupe_key text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Migrazione sicura anche se la tabella V26 esiste già.
alter table public.notification_jobs add column if not exists locked_at timestamptz;
alter table public.notification_jobs add column if not exists updated_at timestamptz not null default now();
alter table public.notification_jobs drop constraint if exists notification_jobs_status_check;
alter table public.notification_jobs add constraint notification_jobs_status_check
  check (status in ('pending','processing','sent','failed','cancelled'));

create index if not exists notification_jobs_due_idx
  on public.notification_jobs(status, scheduled_for);
create index if not exists notification_jobs_booking_idx
  on public.notification_jobs(booking_id);

alter table public.notification_jobs enable row level security;
revoke all on table public.notification_jobs from public, anon, authenticated;

-- Converte il telefono nell'External ID usato da OneSignal nel frontend.
create or replace function public.notification_external_id(p_phone text)
returns text
language sql
immutable
as $$
  select case
    when p_phone is null or p_phone like 'MANUAL-%' then null
    when length(regexp_replace(p_phone, '[^0-9]', '', 'g')) < 8 then null
    else 'cliente_' || regexp_replace(p_phone, '[^0-9]', '', 'g')
  end
$$;

-- Inserisce un job senza generare errori in caso di duplicato.
create or replace function public.enqueue_notification_job(
  p_kind text,
  p_booking_id uuid,
  p_recipient_type text,
  p_recipient_external_id text,
  p_title text,
  p_message text,
  p_scheduled_for timestamptz,
  p_dedupe_key text
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  insert into public.notification_jobs(
    kind, booking_id, recipient_type, recipient_external_id,
    title, message, scheduled_for, dedupe_key
  ) values (
    p_kind, p_booking_id, p_recipient_type, p_recipient_external_id,
    p_title, p_message, p_scheduled_for, p_dedupe_key
  ) on conflict (dedupe_key) do nothing;
end;
$$;

create or replace function public.enqueue_booking_notifications()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  c public.customers%rowtype;
  appointment_at timestamptz;
  ext_id text;
  pretty_date text;
  pretty_time text;
  version_key text;
begin
  select * into c from public.customers where id = new.customer_id;
  appointment_at := (new.booking_date + new.booking_time) at time zone 'Europe/Rome';
  ext_id := public.notification_external_id(c.phone);
  pretty_date := to_char(new.booking_date, 'DD/MM/YYYY');
  pretty_time := to_char(new.booking_time, 'HH24:MI');
  version_key := new.booking_date::text || '-' || replace(new.booking_time::text, ':', '');

  if tg_op = 'INSERT' then
    if new.status = 'confirmed' then
      perform public.enqueue_notification_job(
        'new_booking', new.id, 'admin', null,
        '💈 Nuova prenotazione',
        trim(coalesce(c.first_name,'') || ' ' || coalesce(c.last_name,'')) ||
          ' — ' || pretty_date || ' alle ' || pretty_time || ' — ' || new.service,
        now(), 'admin-new-' || new.id
      );

      if ext_id is not null then
        if appointment_at - interval '24 hours' > now() then
          perform public.enqueue_notification_job(
            'reminder_24h', new.id, 'customer', ext_id,
            'Promemoria appuntamento',
            'Domani alle ' || pretty_time || ' ti aspettiamo da Tranne il Lunedì.',
            appointment_at - interval '24 hours',
            '24h-' || new.id || '-' || version_key
          );
        end if;
        if appointment_at - interval '1 hour' > now() then
          perform public.enqueue_notification_job(
            'reminder_1h', new.id, 'customer', ext_id,
            'Appuntamento tra un’ora',
            'Ti aspettiamo alle ' || pretty_time || ' da Tranne il Lunedì.',
            appointment_at - interval '1 hour',
            '1h-' || new.id || '-' || version_key
          );
        end if;
      end if;
    end if;
    return new;
  end if;

  -- Da qui in poi TG_OP è UPDATE.
  if old.status = 'confirmed' and new.status = 'cancelled' then
    update public.notification_jobs
      set status = 'cancelled', updated_at = now()
      where booking_id = new.id and status in ('pending','processing');

    perform public.enqueue_notification_job(
      'booking_cancelled_admin', new.id, 'admin', null,
      '❌ Prenotazione annullata',
      trim(coalesce(c.first_name,'') || ' ' || coalesce(c.last_name,'')) ||
        ' — ' || pretty_date || ' alle ' || pretty_time,
      now(), 'admin-cancelled-' || new.id
    );

    if ext_id is not null then
      perform public.enqueue_notification_job(
        'customer_cancelled', new.id, 'customer', ext_id,
        'Appuntamento annullato',
        'Il tuo appuntamento del ' || pretty_date || ' alle ' || pretty_time || ' è stato annullato.',
        now(), 'customer-cancelled-' || new.id
      );
    end if;
    return new;
  end if;

  if new.status = 'confirmed'
     and (old.booking_date, old.booking_time) is distinct from (new.booking_date, new.booking_time) then
    update public.notification_jobs
      set status = 'cancelled', updated_at = now()
      where booking_id = new.id
        and status in ('pending','processing')
        and kind in ('reminder_24h','reminder_1h');

    perform public.enqueue_notification_job(
      'booking_moved', new.id, 'admin', null,
      '🔄 Appuntamento spostato',
      trim(coalesce(c.first_name,'') || ' ' || coalesce(c.last_name,'')) ||
        ' → ' || pretty_date || ' alle ' || pretty_time,
      now(), 'admin-moved-' || new.id || '-' || version_key
    );

    if ext_id is not null then
      perform public.enqueue_notification_job(
        'customer_moved', new.id, 'customer', ext_id,
        'Appuntamento aggiornato',
        'Il tuo appuntamento è stato spostato al ' || pretty_date || ' alle ' || pretty_time || '.',
        now(), 'customer-moved-' || new.id || '-' || version_key
      );

      if appointment_at - interval '24 hours' > now() then
        perform public.enqueue_notification_job(
          'reminder_24h', new.id, 'customer', ext_id,
          'Promemoria appuntamento',
          'Domani alle ' || pretty_time || ' ti aspettiamo da Tranne il Lunedì.',
          appointment_at - interval '24 hours',
          '24h-' || new.id || '-' || version_key
        );
      end if;
      if appointment_at - interval '1 hour' > now() then
        perform public.enqueue_notification_job(
          'reminder_1h', new.id, 'customer', ext_id,
          'Appuntamento tra un’ora',
          'Ti aspettiamo alle ' || pretty_time || ' da Tranne il Lunedì.',
          appointment_at - interval '1 hour',
          '1h-' || new.id || '-' || version_key
        );
      end if;
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists bookings_notification_trigger on public.bookings;
create trigger bookings_notification_trigger
after insert or update of booking_date, booking_time, status on public.bookings
for each row execute function public.enqueue_booking_notifications();

-- Prelievo atomico: impedisce invii doppi se due esecuzioni si sovrappongono.
create or replace function public.claim_notification_jobs(p_limit integer default 50)
returns setof public.notification_jobs
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  -- Recupera eventuali job rimasti bloccati per crash della funzione.
  update public.notification_jobs
     set status = 'pending', locked_at = null, updated_at = now()
   where status = 'processing'
     and locked_at < now() - interval '10 minutes';

  return query
  with selected as (
    select id
      from public.notification_jobs
     where status = 'pending'
       and scheduled_for <= now()
     order by scheduled_for, id
     for update skip locked
     limit greatest(1, least(coalesce(p_limit, 50), 100))
  )
  update public.notification_jobs j
     set status = 'processing',
         locked_at = now(),
         attempts = attempts + 1,
         updated_at = now()
    from selected s
   where j.id = s.id
  returning j.*;
end;
$$;

revoke all on function public.claim_notification_jobs(integer) from public, anon, authenticated;

-- Accoda i promemoria per prenotazioni future già presenti.
insert into public.notification_jobs(
  kind, booking_id, recipient_type, recipient_external_id,
  title, message, scheduled_for, dedupe_key
)
select
  'reminder_24h', b.id, 'customer', public.notification_external_id(c.phone),
  'Promemoria appuntamento',
  'Domani alle ' || to_char(b.booking_time,'HH24:MI') || ' ti aspettiamo da Tranne il Lunedì.',
  ((b.booking_date + b.booking_time) at time zone 'Europe/Rome') - interval '24 hours',
  '24h-' || b.id || '-' || b.booking_date || '-' || replace(b.booking_time::text, ':', '')
from public.bookings b
join public.customers c on c.id = b.customer_id
where b.status = 'confirmed'
  and public.notification_external_id(c.phone) is not null
  and ((b.booking_date + b.booking_time) at time zone 'Europe/Rome') - interval '24 hours' > now()
on conflict (dedupe_key) do nothing;

insert into public.notification_jobs(
  kind, booking_id, recipient_type, recipient_external_id,
  title, message, scheduled_for, dedupe_key
)
select
  'reminder_1h', b.id, 'customer', public.notification_external_id(c.phone),
  'Appuntamento tra un’ora',
  'Ti aspettiamo alle ' || to_char(b.booking_time,'HH24:MI') || ' da Tranne il Lunedì.',
  ((b.booking_date + b.booking_time) at time zone 'Europe/Rome') - interval '1 hour',
  '1h-' || b.id || '-' || b.booking_date || '-' || replace(b.booking_time::text, ':', '')
from public.bookings b
join public.customers c on c.id = b.customer_id
where b.status = 'confirmed'
  and public.notification_external_id(c.phone) is not null
  and ((b.booking_date + b.booking_time) at time zone 'Europe/Rome') - interval '1 hour' > now()
on conflict (dedupe_key) do nothing;
